# frozen_string_literal: true

require "cgi"

require_relative "billingio/version"
require_relative "billingio/errors"
require_relative "billingio/http_client"
require_relative "billingio/webhook_signature"
require_relative "billingio/webhook"

# Models
require_relative "billingio/models/checkout"
require_relative "billingio/models/checkout_status"
require_relative "billingio/models/webhook_endpoint"
require_relative "billingio/models/event"
require_relative "billingio/models/health_response"
require_relative "billingio/models/paginated_list"
require_relative "billingio/models/customer"
require_relative "billingio/models/payment_method"
require_relative "billingio/models/payment_link"
require_relative "billingio/models/subscription_plan"
require_relative "billingio/models/subscription"
require_relative "billingio/models/subscription_renewal"
require_relative "billingio/models/entitlement"
require_relative "billingio/models/entitlement_check"
require_relative "billingio/models/payout_intent"
require_relative "billingio/models/settlement"
require_relative "billingio/models/revenue_event"
require_relative "billingio/models/accounting_report"
require_relative "billingio/models/adjustment"

# Resources
require_relative "billingio/resources/checkouts"
require_relative "billingio/resources/webhooks"
require_relative "billingio/resources/events"
require_relative "billingio/resources/health"
require_relative "billingio/resources/customers"
require_relative "billingio/resources/payment_methods"
require_relative "billingio/resources/payment_links"
require_relative "billingio/resources/subscription_plans"
require_relative "billingio/resources/subscriptions"
require_relative "billingio/resources/subscription_renewals"
require_relative "billingio/resources/entitlements"
require_relative "billingio/resources/payout_intents"
require_relative "billingio/resources/settlements"
require_relative "billingio/resources/revenue_events"
require_relative "billingio/resources/adjustments"

require_relative "billingio/client"
